theme = "soho"
baseurl = "https://augustocl.github.io/AugustoLeal/"
languageCode = "en"
title = "AUGUSTO LEAL"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
summarylength = 10
enableEmoji = true
paginate = 5
publishDir = "docs/"
ignoreErrors = ["error-remote-getjson"]

[params]
  title = "Augusto Leal"
  description = ""
  # gravatar = "soho@example.com"
  images = ["images/profile1.png"]
  #profilePicture = "images/picture1.jpg"
  copyright = "Augusto Leal"
  license = "CC BY-SA 4.0"
  licenseURL = "https://creativecommons.org/licenses/by-sa/4.0"
  builtWith = true
  mainSections = ["post"]
  layoutReverse = true
  
  highlightjsVersion = "9.12.0"
  #highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
  highlightjsCDN = "//cdn.bootcss.com"
  highlightjsLang = ["r", "yaml", "julia", "python"]
  highlightjsTheme = "github"
  #MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
  MathJaxCDN = "//cdn.bootcss.com"
  MathJaxVersion = "2.7.5"

## Set custom theme color.
themeColor = "#00004d"  # #000162 #1d2f6b

  [[params.socialIcons]]
  icon = "fa-linkedin"
  title = "Linkedin"
  url = "https://www.linkedin.com/in/augustocleal/"

  [[params.socialIcons]]
  icon = "fa-github"
  title = "GitHub"
  url = "https://github.com/AugustoCL"

[taxonomies]
  series = "series"
  category = "categories"
  tag = "tags"

[menu]

  [[menu.main]]
  name = "Posts"
  weight = 100
  identifier = "post"
  url = "/post/"

  [[menu.main]]
  name = "Categories"
  weight = 200
  identifier = "categories"
  url = "/categories/"

  [[menu.main]]
  name = "Tags"
  weight = 200
  identifier = "tags"
  url = "/tags/"

  [[menu.main]]
  name = "About"
  identifier = "about"
  weight = 10
  url = "/about/"

  [[menu.main]]
  name = "Contact"
  identifier = "contact"
  weight = 20
  url = "/contact/"

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineAnchors = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "monokai"
    tabWidth = 4