---
title: "ALM Solution with SIMPLEX"
author: "AugustoCL"
date: 2020-12-01T21:13:14-05:00
categories: ["R", "julia"]
tags: ["R Markdown", "optimization", "julia", "JuMP", "ALM", "finance"]
---


```{r setup, include=FALSE}
library(JuliaCall)
knitr::opts_chunk$set(echo = TRUE, comment=NA)
julia_setup(JULIA_HOME="C:/Users/augus/AppData/Local/Programs/Julia/Julia-1.6.0/bin")
#julia <- julia_setup()
```

## Julia Chunk
```{julia}
using JuMP, Cbc
```

## Inputs
```{julia}
cash_flow = Float64[100; 200; 800; 100; 800; 1200]
bond_prices = Float64[109.0; 94.8; 99.5; 93.1; 97.2; 92.9; 110.0; 104.0; 102.0; 95.2]
N = length(bond_prices);
Y = length(cash_flow);

C = Float64[10  10  10  10  10  110;
            7   7   7   7   7   170;
            8   8   8   8   8   108;
            6   6   6   6   106 0;
            7   7   7   7   107 0;
            5   5   5   105 0   0;
            10  10  110 0   0   0;
            8   8   108 0   0   0;
            7   107 0   0   0   0;
            100 0   0   0   0   0];
C = Array(C')
```

## SIMPLEX Model
```{julia}
m = JuMP.Model(Cbc.Optimizer);
set_silent(m)

@variable(m, x[1:N] >= 0, Int);
@variable(m, f[1:Y] >= 0);

@constraint(m, con1,    x'*C[1,:]          == cash_flow[1] + f[1]);
@constraint(m, con[i=2:Y], x'*C[i,:] + f[i-1] == cash_flow[i] + f[i]);

@objective(m, Min, x'*bond_prices);

JuMP.optimize!(m);
```

## outputs from model
```{julia}
X_bonds = convert.(Int,round.(value.(x); digits=0))
cost = objective_value(m)
folgas = value.(f)
```

## evaluating and plotting results in R
```{r}
X <- julia_eval("X_bonds")
plot(X, type = "s", xlab = "index", ylab = "N° of Bonds")
```
